name: Deploy Published ASP.Net Core app to Azure Web App - zakariacontacts

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: windows-latest

    permissions:  # Add write permission for id-token
      id-token: write
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_0B2D196906E340ABAC65FE77A4124387 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_439C670D532144FE9CF8F6928FEFC790 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_8DCF2DB928284C3992B826E2692424F7 }}

      - name: Deploy already published app to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'zakariacontacts'  # Replace with your app name
          slot-name: 'Production'
          package: ./publish  # Path to the folder where you uploaded the published files
